### ISSUE TITLE
The test 

### ISSUE THREAD

**Issue by ucavalcante** [MicrosoftLearning/20487D-Developing-Microsoft-Azure-and-Web-Services#136]
Failed to run dotnet test in mod02 lab2 same in solution folder.

dotnet test
Build iniciada, aguarde...
Build concluído.

Execução de teste para c:\Users\ulc\Source\training\20487D-Developing-Microsoft-Azure-and-Web-Services\AllFiles\Mod02\LabFiles\Lab2\Solution\DAL.Test\bin\Debug\netcoreapp2.1\DAL.Test.dll(.NETCoreApp,Version=v2.1)
Ferramenta de Linha de Comando de Execução de Teste da Microsoft (R) Versão 15.9.0
Copyright (c) Microsoft Corporation. Todos os direitos reservados.

Iniciando execução de teste, espere...
AddTwoBookingsTest com falha
Mensagem de erro:
 Test method DAL.Test.BookingRepositoryTests.AddTwoBookingsTest threw exception: 
Microsoft.Data.Sqlite.SqliteException: SQLite Error 14: 'unable to open database file'.
Rastreamento de pilha:
    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at DAL.Database.DbInitializer.Initialize(MyDbContext context) in c:\Users\ulc\Source\training\20487D-Developing-Microsoft-Azure-and-Web-Services\AllFiles\Mod02\LabFiles\Lab2\Solution\DAL\Database\DbInitializer.cs:line 11
   at DAL.Database.MyDbContext.InitialDBContext() in c:\Users\ulc\Source\training\20487D-Developing-Microsoft-Azure-and-Web-Services\AllFiles\Mod02\LabFiles\Lab2\Solution\DAL\Database\MyDbContext.cs:line 15
   at DAL.Database.MyDbContext..ctor(DbContextOptions`1 options) in c:\Users\ulc\Source\training\20487D-Developing-Microsoft-Azure-and-Web-Services\AllFiles\Mod02\LabFiles\Lab2\Solution\DAL\Database\MyDbContext.cs:line 21
   at DAL.Repository.HotelBookingRepository.Add(Int32 travelerId, Int32 roomId, DateTime checkIn, Int32 guest) in c:\Users\ulc\Source\training\20487D-Developing-Microsoft-Azure-and-Web-Services\AllFiles\Mod02\LabFiles\Lab2\Solution\DAL\Repository\HotelBookingRepository.cs:line 29
   at DAL.Test.BookingRepositoryTests.AddTwoBookingsTest() in c:\Users\ulc\Source\training\20487D-Developing-Microsoft-Azure-and-Web-Services\AllFiles\Mod02\LabFiles\Lab2\Solution\DAL.Test\BookingRepositoryTests.cs:line 33

AddTwoBookingsSQLLiteTest com falha
Mensagem de erro:
 Test method DAL.Test.BookingRepositoryTests.AddTwoBookingsSQLLiteTest threw exception: 
Microsoft.Data.Sqlite.SqliteException: SQLite Error 14: 'unable to open database file'.
Rastreamento de pilha:
    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at DAL.Database.DbInitializer.Initialize(MyDbContext context) in c:\Users\ulc\Source\training\20487D-Developing-Microsoft-Azure-and-Web-Services\AllFiles\Mod02\LabFiles\Lab2\Solution\DAL\Database\DbInitializer.cs:line 11
   at DAL.Database.MyDbContext.InitialDBContext() in c:\Users\ulc\Source\training\20487D-Developing-Microsoft-Azure-and-Web-Services\AllFiles\Mod02\LabFiles\Lab2\Solution\DAL\Database\MyDbContext.cs:line 15
   at DAL.Database.MyDbContext..ctor(DbContextOptions`1 options) in c:\Users\ulc\Source\training\20487D-Developing-Microsoft-Azure-and-Web-Services\AllFiles\Mod02\LabFiles\Lab2\Solution\DAL\Database\MyDbContext.cs:line 21
   at DAL.Test.BookingRepositoryTests.AddTwoBookingsSQLLiteTest() in c:\Users\ulc\Source\training\20487D-Developing-Microsoft-Azure-and-Web-Services\AllFiles\Mod02\LabFiles\Lab2\Solution\DAL.Test\BookingRepositoryTests.cs:line 52

Total de testes: 2. Aprovados: 0. Com falha: 2. Ignorados: 0.
Falha na Execução de Teste.
Tempo de execução de teste: 10,3408 Segundos

**Comment by TesterTesterson1004** [comment]
Apologies for my lack of Portuguese, but I was troubleshooting a similar error today - initially I was able to repro what looked identical to the error you reference here, however in my 2nd run-through of the same Lab B in a fresh VM instance I _was_ able to get all the instructions (using 20487D_MOD02_LAK.md) to run successfully - so you should be able to get it to run successfully too.

You may have seen the failure for different reasons, but there were 2 primary things that I realized caused the error in my case:

1.)  I have never used Visual Studio Code app before, and absent specific steps in the LAK referring to 'saving' the new code entered from the instructions, I did not initially do so.  Thus, when I ran it first I received an error.  

-- In my second successful run through, I insured that I did a 'File\Save All' in VS Code just before any of the steps in CMD-prompt to restore/build/run.


2.)  In some cases, since I am not a Developer, I was uncertain exactly where to paste the code referenced in the LAK within the existing 'Starter' app.  In these cases, it is very useful to open up the same file from the 'Solution' directory where a completed/running app is present as a 'known good' reference.

-- For example, you can refer to the file 'BookingRepositoryTests.cs' in <drive>:\Allfiles\Mod02\Labfiles\Lab2\Solution\DAL.Test directory.


One last thing to look out for - I *almost* made this mistake too:  When pasting the code in Lab B/Exercise 2/Task 3/Step 8 - be certain you have updated the '[Repository Root]' with the your drive letter. 

For example:

.UseSqlite(@"Data Source = **C:**\Allfiles\Mod02\LabFiles\Lab2\Database\SqliteHotel.db")

**Comment by AviAvni** [comment]
@ucavalcante did @TesterTesterson1004 helped you can you give more information?
